In [70]:
import pandas as pd
import numpy as np
import math

In [60]:
buurt_data = pd.read_excel('Hague_cijfers.xlsx',sheet_name='Meest-recent')

In [24]:
buurt_data.head()

,Naam van het gebied,Soort regio,Codering,Aantal inwoners,Mannen,Vrouwen,0 tot 15 jaar,15 tot 25 jaar,25 tot 45 jaar,45 tot 65 jaar,...,Scholen binnen 3 km,Oppervlakte totaal,Oppervlakte land,Oppervlakte water,Meest voorkomende postcode,Dekkingspercentage,Mate van stedelijkheid,Omgevingsadressendichtheid,Indelingswijziging wijken en buurten,Gemeentenaam
0,Den Haag,Gemeente,GM0518,532561,263975,268586,92599,65311,161052,137189,...,35.4,9813,8245,1568,0,NaN,1,4856,.,Den Haag
1,Wijk 01 Oostduinen,Wijk,WK051801,0,0,0,0,0,0,0,...,NaN,318,308,10,0,NaN,4,682,1,Den Haag
2,Oostduinen,Buurt,BU05180170,0,0,0,0,0,0,0,...,NaN,318,308,10,2597,4.0,4,682,1,Den Haag
3,Wijk 02 Belgisch Park,Wijk,WK051802,8205,4030,4175,1245,1215,1775,2320,...,10.4,106,106,0,0,NaN,2,2446,1,Den Haag
4,Belgisch Park,Buurt,BU05180271,8205,4030,4175,1245,1215,1775,2320,...,10.4,106,106,0,2587,3.0,2,2446,1,Den Haag

In [61]:
buurt_data.rename(columns = {'Soort regio':'type','Naam van het gebied':'Name'}, inplace = True)

In [62]:
nl_tert_25to34 = 0.41
nl_tert_55to64 = 0.27
nl_tert_ratio_youngtoold = nl_tert_25to34/nl_tert_55to64

In [63]:
#buurt_data=buurt_data.rename(columns = {'Soort_regio':'type','Naam van het gebied':'Name'}, inplace = True) 
wijk = ''
buurt_data['Nearest wijk'] = 'Den Haag'
for i in range (0,len(buurt_data)):
    if (buurt_data.loc[i,'type'] == 'Wijk'):
        wijk = buurt_data.loc[i,'Name']
    buurt_data.loc[i,'Nearest wijk'] = wijk
buurt_data['Wijk no'] = buurt_data['Nearest wijk'].str.split(" ",n=2,expand=True)[1]

In [64]:
hague_primary_rate = '33'
hague_secondary_rate = '36'
hague_tertiary_rate = '31'
education = pd.read_csv('Education.csv')
education['Wijk no'] = education['Wijken'].str.split(" ",n = 1, expand = True)[0]
buurt_data_with_edu = buurt_data.merge(education,on=['Wijk no'])

In [65]:
buurt_data_needed = buurt_data_with_edu[['Name','type','Codering','Aantal inwoners','Mannen',
                                       'Vrouwen','0 tot 15 jaar','15 tot 25 jaar','25 tot 45 jaar', '45 tot 65 jaar',
                                       '65 jaar of ouder','Wijken',
                                       'Opleidingsniveau Laag|2017', 'Opleidingsniveau Middelbaar|2017',
                                       'Opleidingsniveau Hoog|2017']]
buurt_data_needed.columns =['Name','Type','Code','Population','Man','Woman','0 to 15 year','15 to 25 year','25 to 45 year',
                            '45 to 65 year','65 year or older','Wijken',
                           'Primary education','Secondary education','Tertiary education']

In [66]:
buurt_data_needed['Primary education'] = buurt_data_needed['Primary education'].fillna(hague_primary_rate)
buurt_data_needed['Secondary education'] = buurt_data_needed['Secondary education'].fillna(hague_secondary_rate)
buurt_data_needed['Tertiary education'] = buurt_data_needed['Tertiary education'].fillna(hague_tertiary_rate)
buurt_data_needed['Primary education'].replace({"x":hague_primary_rate}, inplace=True)
buurt_data_needed['Secondary education'].replace({"x":hague_secondary_rate}, inplace=True)
buurt_data_needed['Tertiary education'].replace({"x":hague_tertiary_rate}, inplace=True)

C:\Users\patel\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Users\patel\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\patel\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [67]:
buurt_data_needed['Primary education'] = 0.01*buurt_data_needed['Primary education'].astype('float')
buurt_data_needed['Secondary education'] = 0.01*buurt_data_needed['Secondary education'].astype('float')
buurt_data_needed['Tertiary education'] = 0.01*buurt_data_needed['Tertiary education'].astype('float')
buurt_data_needed['60 to 70 year'] = buurt_data_needed['45 to 65 year']*(1/4) + buurt_data_needed['65 year or older']*(5/17)
buurt_data_needed['70 year or older'] = buurt_data_needed['65 year or older']*(12/17) 
buurt_data_needed['less than 40'] =  buurt_data_needed['0 to 15 year']+ buurt_data_needed['15 to 25 year'] + (3/4)*buurt_data_needed['25 to 45 year']
buurt_data_needed['more than 40'] = buurt_data_needed['Population'] - buurt_data_needed['less than 40']
buurt_data_needed['old_literacy_rate'] = (buurt_data_needed['Tertiary education']*buurt_data_needed['Population'])/(buurt_data_needed['more than 40'] + nl_tert_ratio_youngtoold*(buurt_data_needed['less than 40']))
buurt_data_needed['young_literacy_rate'] = buurt_data_needed['old_literacy_rate'] *nl_tert_ratio_youngtoold
buurt_data_needed['40 to 60 year'] = buurt_data_needed['Population']-buurt_data_needed['less than 40']-buurt_data_needed['60 to 70 year']- buurt_data_needed['70 year or older']

C:\Users\patel\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Users\patel\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\patel\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\patel\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
C:\Users\patel\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
C:\Users\patel\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\patel\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
C:\Users\patel\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\patel\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
C:\Users\patel\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.

In [59]:
buurt_data_needed['male less than 40'] = buurt_data_needed['less than 40']*buurt_data_needed['Man']/buurt_data_needed['Population']
buurt_data_needed['female less than 40'] = buurt_data_needed['less than 40']*buurt_data_needed['Woman']/buurt_data_needed['Population']
buurt_data_needed['male 40 to 60'] = buurt_data_needed['40 to 60 year']*buurt_data_needed['Man']/buurt_data_needed['Population']
buurt_data_needed['female 40 to 60'] = buurt_data_needed['40 to 60 year']*buurt_data_needed['Woman']/buurt_data_needed['Population']
buurt_data_needed['male 60 to 70'] = buurt_data_needed['60 to 70 year']*buurt_data_needed['Man']/buurt_data_needed['Population']
buurt_data_needed['female 60 to 70'] = buurt_data_needed['60 to 70 year']*buurt_data_needed['Woman']/buurt_data_needed['Population']
buurt_data_needed['male more than 70'] = buurt_data_needed['70 year or older']*buurt_data_needed['Man']/buurt_data_needed['Population']
buurt_data_needed['female more than 70'] = buurt_data_needed['70 year or older']*buurt_data_needed['Woman']/buurt_data_needed['Population']
buurt_data_needed['male 40 to 60'] = buurt_data_needed['40 to 60 year']*buurt_data_needed['Man']/buurt_data_needed['Population']
buurt_data_needed['female 40 to 60'] = buurt_data_needed['40 to 60 year']*buurt_data_needed['Woman']/buurt_data_needed['Population']
buurt_data_needed['male 60 to 70'] = buurt_data_needed['60 to 70 year']*buurt_data_needed['Man']/buurt_data_needed['Population']
buurt_data_needed['female 60 to 70'] = buurt_data_needed['60 to 70 year']*buurt_data_needed['Woman']/buurt_data_needed['Population']
buurt_data_needed['male more than 70'] = buurt_data_needed['70 year or older']*buurt_data_needed['Man']/buurt_data_needed['Population']
buurt_data_needed['female more than 70'] = buurt_data_needed['70 year or older']*buurt_data_needed['Woman']/buurt_data_needed['Population']

0.74

In [ ]:
buurt_data_needed['male less than 40 educated'] = buurt_data_needed['male less than 40']*buurt_data_needed['young_literacy_rate']
buurt_data_needed['male less than 40 uneducated'] = buurt_data_needed['male less than 40']*(1-buurt_data_needed['young_literacy_rate'])
buurt_data_needed['female less than 40 educated'] = buurt_data_needed['female less than 40']*buurt_data_needed['young_literacy_rate']
buurt_data_needed['female less than 40 uneducated'] = buurt_data_needed['female less than 40']*(1-buurt_data_needed['young_literacy_rate'])
buurt_data_needed['male 40 to 60 educated'] = buurt_data_needed['male 40 to 60']*buurt_data_needed['old_literacy_rate']
buurt_data_needed['male 40 to 60 uneducated'] = buurt_data_needed['male 40 to 60']*(1-buurt_data_needed['old_literacy_rate'])
buurt_data_needed['female 40 to 60 educated'] = buurt_data_needed['female 40 to 60']*buurt_data_needed['old_literacy_rate']
buurt_data_needed['female 40 to 60 uneducated'] = buurt_data_needed['female 40 to 60']*(1-buurt_data_needed['old_literacy_rate'])
buurt_data_needed['male 60 to 70 educated'] = buurt_data_needed['male 60 to 70']*buurt_data_needed['old_literacy_rate']
buurt_data_needed['male 60 to 70 uneducated'] = buurt_data_needed['male 60 to 70']*(1-buurt_data_needed['old_literacy_rate'])
buurt_data_needed['female 60 to 70 educated'] = buurt_data_needed['female 60 to 70']*buurt_data_needed['old_literacy_rate']
buurt_data_needed['female 60 to 70 uneducated'] = buurt_data_needed['female 60 to 70']*(1-buurt_data_needed['old_literacy_rate'])
buurt_data_needed['male more than 70 educated'] = buurt_data_needed['male more than 70']*buurt_data_needed['old_literacy_rate']
buurt_data_needed['male more than 70 uneducated'] = buurt_data_needed['male more than 70']*(1-buurt_data_needed['old_literacy_rate'])
buurt_data_needed['female more than 70 educated'] = buurt_data_needed['female more than 70']*buurt_data_needed['old_literacy_rate']
buurt_data_needed['female more than 70 uneducated'] = buurt_data_needed['female more than 70']*(1-buurt_data_needed['old_literacy_rate'])
buurt_data_needed['male less than 60 educated'] = buurt_data_needed['male less than 40 educated'] + buurt_data_needed['male 40 to 60 educated']
buurt_data_needed['male less than 60 uneducated'] = buurt_data_needed['male less than 40 uneducated'] + buurt_data_needed['male 40 to 60 uneducated']
buurt_data_needed['female less than 60 educated'] = buurt_data_needed['female less than 40 educated'] + buurt_data_needed['female 40 to 60 educated']
buurt_data_needed['female less than 60 uneducated'] = buurt_data_needed['female less than 40 uneducated'] + buurt_data_needed['female 40 to 60 uneducated']

In [98]:
buurt_data['income per household'] = buurt_data['Gemiddeld inkomen per inkomensontvangerÂ ']/12
buurt_data_needed['income per household'] = np.array(buurt_data['income per household'])[1:159]

C:\Users\patel\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [102]:
for i in range (0,len(buurt_data_needed)):
#    income = buurt_data_needed.loc[i,'income per household']
    income = 0
    buurt_data_needed.loc[i,'prob_male less than 60 educated'] = 1/(1 + math.exp(-1*(-0.032+0.159 + 0.059+ 0.017*income)))
    buurt_data_needed.loc[i,'prob_male less than 60 uneducated'] = 1/(1 + math.exp(-1*(-0.032+0.0 + 0.059+ 0.017*income)))
    buurt_data_needed.loc[i,'prob_female less than 60 educated'] = 1/(1 + math.exp(-1*(-0.0+0.159 + 0.059+ 0.017*income)))
    buurt_data_needed.loc[i,'prob_female less than 60 uneducated'] = 1/(1 + math.exp(-1*(-0.0+0.0 + 0.059+ 0.017*income)))
    buurt_data_needed.loc[i,'prob_male 60 to 70 educated'] = 1/(1 + math.exp(-1*(-0.032+0.159 + 0.059+ 0.017*income-0.243)))
    buurt_data_needed.loc[i,'prob_male 60 to 70 uneducated'] = 1/(1 + math.exp(-1*(-0.032+0.0 + 0.059+ 0.017*income-0.243)))
    buurt_data_needed.loc[i,'prob_female 60 to 70 educated'] = 1/(1 + math.exp(-1*(-0.0+0.159 + 0.059+ 0.017*income-0.243)))
    buurt_data_needed.loc[i,'prob_female 60 to 70 uneducated'] = 1/(1 + math.exp(-1*(-0.0+0.0 + 0.059+ 0.017*income-0.243)))
    buurt_data_needed.loc[i,'prob_male more than 60 educated'] = 1/(1 + math.exp(-1*(-0.032+0.159 + 0.059+ 0.017*income-0.067)))
    buurt_data_needed.loc[i,'prob_male more than 60 uneducated'] = 1/(1 + math.exp(-1*(-0.032+0.0 + 0.059+ 0.017*income-0.067)))
    buurt_data_needed.loc[i,'prob_female more than 60 educated'] = 1/(1 + math.exp(-1*(-0.0+0.159 + 0.059+ 0.017*income-0.067)))
    buurt_data_needed.loc[i,'prob_female more than 60 uneducated'] = 1/(1 + math.exp(-1*(-0.0+0.0 + 0.059+ 0.017*income-0.067)))

In [104]:
buurt_data_needed['prob_male less than 60 educated'].max()

0.5463664026742796