In [70]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [100]:
predictors = pd.read_csv('C:/Users/patel/Thesis/DataCleaning/Food/RF/inputdata.csv')
predicted = pd.read_csv('cereals_consume.csv')

In [101]:
predicted = predicted[['TIME','GEO','CROPS','Value']]
typeof = 'CROPS'
predicted_reformat = pd.DataFrame()
number_of_col = 1
for type_unique in predicted[typeof].unique():
    if (number_of_col == 1):
        predicted_unique = predicted[predicted[typeof]==type_unique]
        predicted_reformat['TIME'] = predicted_unique['TIME']
        predicted_reformat['GEO'] = predicted_unique['GEO']
        predicted_unique['Value'].replace({":":0}, inplace=True) 
        predicted_reformat[type_unique] = predicted_unique['Value'].replace({' ':''},regex=True).astype('float')
        predicted_reformat = predicted_reformat[predicted_reformat[type_unique] != 0]
        number_of_col = number_of_col + 1
    else:
        predicted_unique = predicted[predicted[typeof]==type_unique]
        predicted_unique['Value'].replace({":":0}, inplace=True) 
        predicted_unique['Value'].replace({":":0}, inplace=True) 
        predicted_unique[type_unique] = predicted_unique['Value'].replace({' ':''},regex=True).astype('float')
        predicted_unique = predicted_unique[predicted_unique[type_unique] != 0]
        predicted_reformat = predicted_reformat.merge(predicted_unique[['TIME','GEO',type_unique]],on=['TIME','GEO'],how='inner')
predicted_reformat['Total_consumed'] = predicted_reformat.iloc[:,2:].sum(axis=1)
predicted_reformat = predicted_reformat[['TIME','GEO','Total_consumed']]
predicted_reformat=predicted_reformat[((predicted_reformat['Total_consumed'] - predicted_reformat['Total_consumed'].mean()) / predicted_reformat['Total_consumed'].std()).abs() < 2]
input_output = pd.merge(predictors,predicted_reformat,on=['TIME','GEO'],how='inner')

C:\Users\patel\Anaconda3\lib\site-packages\ipykernel_launcher.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [102]:
input_output

,TIME,GEO,male_percent,female_percent,0 to 15 percent,15 to 25 percent,25 to 45 percent,45 to 65 percent,65 or older percent,Primary,Secondary,Tertiary,activity_level,Income,Total_pop,Total_consumed
0,2011,Belgium,0.491037,0.508963,0.169744,0.121185,0.268566,0.269316,0.171188,0.319,0.377,0.304,0.66700,19950.0,11000638,20.02
1,2011,Bulgaria,0.487002,0.512998,0.132321,0.118057,0.282821,0.282193,0.184607,0.240,0.559,0.201,0.65900,2911.0,7369431,51.03
2,2011,Czechia,0.490833,0.509167,0.145113,0.119758,0.305142,0.273888,0.156099,0.139,0.703,0.158,0.70525,7451.0,10486731,289.33
3,2011,Denmark,0.495732,0.504268,0.178952,0.124793,0.260265,0.268063,0.167927,0.309,0.413,0.278,0.77775,26944.0,5560628,513.07
4,2011,Germany (until 1990 former territory of the FRG),0.487704,0.512296,0.135669,0.111234,0.258918,0.287548,0.206632,0.181,0.576,0.243,0.77300,19043.0,80222065,3216.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
264,2019,Sweden,0.502673,0.497327,0.177878,0.113107,0.264650,0.245374,0.198991,0.208,0.416,0.376,0.82925,NaN,10230185,938.20
265,2019,United Kingdom,0.493660,0.506340,0.179152,0.117518,0.261199,0.257991,0.184140,0.194,0.404,0.402,0.78150,NaN,66647112,1137.02
266,2019,Switzerland,0.495887,0.504113,0.150242,0.106402,0.277168,0.281590,0.184598,0.167,0.449,0.384,0.84325,NaN,8544527,21.30
267,2019,North Macedonia,0.500787,0.499213,0.163666,0.123590,0.305090,0.267028,0.140627,0.311,0.509,0.180,0.66250,NaN,2077132,15.52
268,2019,Serbia,0.487209,0.512791,0.143055,0.105336,0.270166,0.277230,0.204212,0.224,0.570,0.206,0.68150,NaN,6963764,69.20

In [86]:
input_output['Per capita consumption'] = input_output['Total_consumed']*1000000/input_output['Total_pop']
final_input_output = input_output.drop(['Total_pop','Total_consumed'],axis=1)
final_input_output=final_input_output[((final_input_output['Per capita consumption'] - final_input_output['Per capita consumption'].mean()) / final_input_output['Per capita consumption'].std()).abs() < 2]
final_input_output.to_csv('final_input_output.csv',index=False)